# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-06-26 05:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ajax_demo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_adress',
            new_name='email_address',
        ),
    ]
